### PR TITLE
Create okh-OttoDIY.yml

### PR DESCRIPTION
**Pull request by jbon**
Hi!

[Jérémy](https://github.com/jbon) here, part of the  [Open Know How](https://openknowhow.org/) working group.  We've come up with a system where a simple file with metadata about a certain project would live in the project documentation page.

From there we are working to create a web-crawler that is going to find these files and index them (the ultimate goal would be to have something like a "hardware" tab on google search (as other search engines). 

I took the liberty of creating one of these files for your project, with the bare minimum for it to be indexed in the future! I hope you don't mind! (it is just this .yml file that should live in the root of the repository). Consequently to the creation of this file, your project should be indexed in our open hardware search page [https://okh.now.sh](https://okh.now.sh/).

I created this, because I think this is a useful project and it would be great to have it listed on the Open Know-how repository, so that it would be even easier for other people to find it!

You can find more technical information about Open Know How [here](https://app.standardsrepo.com/MakerNetAlliance/OpenKnowHow/wiki)

### CODE REVIEW

**Comment by jbon** [comment]
@cparrapa could you check whether the information I put in the file is correct?

And it would be great if you could provide some additional information to complete the metadata, especially
- a permanent link to an image of OttoDIY
- licensing terms for the hardware and software (I only found those of the documentation [CC-BY-SA 4.0])
- a contact email address either for yourself or your OttoDIY Workshop organisation.

Thanks! :gift_heart:






please check and accept pull request

**Comment by jbon** [comment]
Also @cparrapa : we could eventually host this file somewhere else if you think it is more appropriate. For example on your Wikifactory account or your own website

**Comment by cparrapa** [comment]
Hi @jbon 
Looks good to me, cool feature to help search engines fin the project. 

- It seems you already put a permanent link to the picture
- Licensing terms i was hoping to get some advice with this program, because all the time i just stayed CC-BY-SA thinking applies to hardware as well, for the software blockly in particular we have the GNU one, for code MIT sometimes got mixed with BSD. I would like to have some consistency here.

Thanks!

**Comment by jbon** [comment]
Cool, thanks! Yes in the meantime I just found the way to add a photo by myself.
Hope you'll find the right way for the licenses. The topic always pretty much confuses me as well :dizzy_face:

**Pull request merged**
